'use client'

import { useRef, useState } from 'react'
import { Upload, FileText, CheckCircle, XCircle, Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import { dynsecApi } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'

type Status = 'idle' | 'uploading' | 'success' | 'error'

export default function ImportPasswordPage() {
  const [file, setFile] = useState<File | null>(null)
  const [status, setStatus] = useState<Status>('idle')
  const [message, setMessage] = useState('')
  const inputRef = useRef<HTMLInputElement>(null)

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0] || null
    setFile(f)
    setStatus('idle')
    setMessage('')
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    const f = e.dataTransfer.files[0]
    if (f) {
      setFile(f)
      setStatus('idle')
    }
  }

  const handleSubmit = async () => {
    if (!file) return
    setStatus('uploading')
    try {
      const formData = new FormData()
      formData.append('file', file)
      const res = await dynsecApi.importPassword(formData)

      if (res.ok) {
        setStatus('success')
        setMessage('Password file imported successfully')
        toast.success('Password file imported successfully')
      } else {
        const text = await res.text()
        setStatus('error')
        setMessage(text || 'Import failed')
        toast.error('Import failed')
      }
    } catch {
      setStatus('error')
      setMessage('Failed to connect to the API')
      toast.error('Failed to connect to the API')
    }
  }

  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h1 className="text-2xl font-bold">Import Password File</h1>
        <p className="text-muted-foreground text-sm">
          Import a Mosquitto password file to add users to dynamic security
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Upload Password File</CardTitle>
          <CardDescription>
            Select a password file generated by <code className="text-xs bg-muted px-1 rounded">mosquitto_passwd</code>
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div
            onDrop={handleDrop}
            onDragOver={(e) => e.preventDefault()}
            onClick={() => inputRef.current?.click()}
            className="border-2 border-dashed rounded-lg p-8 text-center cursor-pointer hover:bg-muted/50 transition-colors"
          >
            <input
              ref={inputRef}
              type="file"
              className="hidden"
              onChange={handleFileChange}
              accept=".txt,.passwd,*"
            />
            {file ? (
              <div className="flex flex-col items-center gap-2">
                <FileText className="h-10 w-10 text-primary" />
                <p className="font-medium">{file.name}</p>
                <p className="text-xs text-muted-foreground">{(file.size / 1024).toFixed(1)} KB</p>
              </div>
            ) : (
              <div className="flex flex-col items-center gap-2 text-muted-foreground">
                <Upload className="h-10 w-10" />
                <p className="font-medium">Drop file here or click to browse</p>
                <p className="text-xs">Accepts Mosquitto password files</p>
              </div>
            )}
          </div>

          {status !== 'idle' && (
            <div className={`flex items-center gap-2 p-3 rounded-lg text-sm ${
              status === 'success' ? 'bg-green-500/10 text-green-700 dark:text-green-400' :
              status === 'error' ? 'bg-destructive/10 text-destructive' :
              'bg-muted text-muted-foreground'
            }`}>
              {status === 'success' && <CheckCircle className="h-4 w-4 shrink-0" />}
              {status === 'error' && <XCircle className="h-4 w-4 shrink-0" />}
              {status === 'uploading' && <Loader2 className="h-4 w-4 animate-spin shrink-0" />}
              <span>{status === 'uploading' ? 'Importing...' : message}</span>
            </div>
          )}

          <Button
            onClick={handleSubmit}
            disabled={!file || status === 'uploading'}
            className="w-full"
          >
            {status === 'uploading' ? (
              <><Loader2 className="h-4 w-4 animate-spin" /> Importing...</>
            ) : (
              <><Upload className="h-4 w-4" /> Import Password File</>
            )}
          </Button>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-sm">How to generate a password file</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          <p className="text-sm text-muted-foreground">Use the mosquitto_passwd utility:</p>
          <div className="bg-muted rounded-md p-3 font-mono text-xs space-y-1">
            <p># Create a new password file</p>
            <p>mosquitto_passwd -c /tmp/pwfile user1</p>
            <p># Add more users</p>
            <p>mosquitto_passwd /tmp/pwfile user2</p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
