'use client'

import { useCallback, useEffect, useState, useRef } from 'react'
import { RefreshCw, Loader2, Save, Upload, FileText, CheckCircle, XCircle, RotateCcw, Server } from 'lucide-react'
import { toast } from 'sonner'
import { Separator } from '@/components/ui/separator'
import { configApi, dynsecApi } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Textarea } from '@/components/ui/textarea'

type Status = 'idle' | 'uploading' | 'success' | 'error'

function BrokerConfigSection() {
  const [config, setConfig] = useState('')
  const [original, setOriginal] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [isSaving, setIsSaving] = useState(false)

  const fetchConfig = useCallback(async () => {
    setIsLoading(true)
    try {
      const data = await configApi.getMosquittoConfig()
      const content = data.config || data.content || ''
      setConfig(content)
      setOriginal(content)
    } catch {
      toast.error('Failed to load Mosquitto configuration')
    } finally {
      setIsLoading(false)
    }
  }, [])

  useEffect(() => { fetchConfig() }, [fetchConfig])

  const handleSave = async () => {
    setIsSaving(true)
    try {
      await configApi.saveMosquittoConfig({ config })
      setOriginal(config)
      toast.success('Configuration saved successfully')
    } catch {
      toast.error('Failed to save configuration')
    } finally {
      setIsSaving(false)
    }
  }

  const isDirty = config !== original

  return (
    <Card>
      <CardHeader>
        <CardTitle>mosquitto.conf</CardTitle>
        <CardDescription>
          Edit the Mosquitto broker configuration. Changes require a broker restart to take effect.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {isLoading ? (
          <div className="flex items-center justify-center h-64">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
          </div>
        ) : (
          <Textarea
            value={config}
            onChange={(e) => setConfig(e.target.value)}
            className="font-mono text-sm min-h-[240px] resize-none"
            placeholder="# Mosquitto configuration"
            spellCheck={false}
          />
        )}
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={fetchConfig} disabled={isLoading}>
            <RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
            Reload
          </Button>
          {isDirty && (
            <Button variant="outline" size="sm" onClick={() => setConfig(original)}>
              <RotateCcw className="h-4 w-4" />
              Reset
            </Button>
          )}
          <Button size="sm" onClick={handleSave} disabled={isSaving || !isDirty}>
            {isSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
            Save
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}

function ImportPasswordSection() {
  const [file, setFile] = useState<File | null>(null)
  const [status, setStatus] = useState<Status>('idle')
  const [message, setMessage] = useState('')
  const inputRef = useRef<HTMLInputElement>(null)

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0] || null
    setFile(f)
    setStatus('idle')
    setMessage('')
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    const f = e.dataTransfer.files[0]
    if (f) { setFile(f); setStatus('idle') }
  }

  const handleSubmit = async () => {
    if (!file) return
    setStatus('uploading')
    try {
      const formData = new FormData()
      formData.append('file', file)
      const res = await dynsecApi.importPassword(formData)
      if (res.ok) {
        setStatus('success')
        setMessage('Password file imported successfully')
        toast.success('Password file imported successfully')
      } else {
        const text = await res.text()
        setStatus('error')
        setMessage(text || 'Import failed')
        toast.error('Import failed')
      }
    } catch {
      setStatus('error')
      setMessage('Failed to connect to the API')
      toast.error('Failed to connect to the API')
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Import Password File</CardTitle>
        <CardDescription>
          Upload a password file generated by <code className="text-xs bg-muted px-1 rounded">mosquitto_passwd</code>
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div
          onDrop={handleDrop}
          onDragOver={(e) => e.preventDefault()}
          onClick={() => inputRef.current?.click()}
          className="border-2 border-dashed rounded-lg p-8 text-center cursor-pointer hover:bg-muted/50 transition-colors"
        >
          <input ref={inputRef} type="file" className="hidden" onChange={handleFileChange} accept=".txt,.passwd,*" />
          {file ? (
            <div className="flex flex-col items-center gap-2">
              <FileText className="h-10 w-10 text-primary" />
              <p className="font-medium">{file.name}</p>
              <p className="text-xs text-muted-foreground">{(file.size / 1024).toFixed(1)} KB</p>
            </div>
          ) : (
            <div className="flex flex-col items-center gap-2 text-muted-foreground">
              <Upload className="h-10 w-10" />
              <p className="font-medium">Drop file here or click to browse</p>
              <p className="text-xs">Accepts Mosquitto password files</p>
            </div>
          )}
        </div>

        {status !== 'idle' && (
          <div className={`flex items-center gap-2 p-3 rounded-lg text-sm ${
            status === 'success' ? 'bg-green-500/10 text-green-700 dark:text-green-400' :
            status === 'error' ? 'bg-destructive/10 text-destructive' :
            'bg-muted text-muted-foreground'
          }`}>
            {status === 'success' && <CheckCircle className="h-4 w-4 shrink-0" />}
            {status === 'error' && <XCircle className="h-4 w-4 shrink-0" />}
            {status === 'uploading' && <Loader2 className="h-4 w-4 animate-spin shrink-0" />}
            <span>{status === 'uploading' ? 'Importing...' : message}</span>
          </div>
        )}

        <Button onClick={handleSubmit} disabled={!file || status === 'uploading'} className="w-full">
          {status === 'uploading'
            ? <><Loader2 className="h-4 w-4 animate-spin" /> Importing...</>
            : <><Upload className="h-4 w-4" /> Import Password File</>
          }
        </Button>
      </CardContent>
    </Card>
  )
}

export default function BrokerSettingsPage() {
  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Server className="h-6 w-6" />
          Broker
        </h1>
        <p className="text-muted-foreground text-sm">Mosquitto broker configuration and password management</p>
      </div>

      <BrokerConfigSection />
      <Separator className="my-2" />
      <ImportPasswordSection />
    </div>
  )
}
